# Generated by Django 3.1.1 on 2020-09-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('imagen', models.FileField(upload_to='projects')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.autores')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.categoria')),
            ],
        ),
    ]
