# Generated by Django 3.1.1 on 2020-09-02 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_slider'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='palabra2',
            new_name='frase2',
        ),
    ]
