# Generated by Django 3.1.1 on 2020-09-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20200902_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='duracion',
            field=models.IntegerField(default=9),
        ),
    ]
