# Generated by Django 3.1.1 on 2020-09-03 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_slider_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='text_size',
            field=models.IntegerField(default=100),
        ),
    ]
