# Generated by Django 3.1.1 on 2020-09-03 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_slider_text_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='color_interfaz',
            field=models.CharField(choices=[('Verde', '/static/css/colors/green.css'), ('Verde', '/static/css/colors/green.css')], default='Verde', max_length=20),
        ),
    ]
