# Generated by Django 3.1.1 on 2020-09-04 17:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20200903_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='Historia')),
                ('fecha', models.DateField()),
                ('contenido', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.AlterField(
            model_name='principal',
            name='color_interfaz',
            field=models.CharField(choices=[('/static/css/colors/green.css', 'Verde'), ('/static/css/colors/mossgreen.css', 'Verde Mostaza'), ('/static/css/colors/bridge.css', 'Verde Claro'), ('/static/css/colors/orange.css', 'Naranja'), ('/static/css/colors/pink.css', 'Rosado'), ('/static/css/colors/red.css', 'Rojo'), ('/static/css/colors/purple.css', 'Morado'), ('/static/css/colors/yellow.css', 'Amarillo'), ('/static/css/colors/violet.css', 'Violeta'), ('/static/css/colors/cyan.css', 'Cyan'), ('/static/css/colors/azul.css', 'Azul')], default='Verde', max_length=100),
        ),
    ]
