# Generated by Django 3.1.1 on 2020-09-04 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_historia_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historia',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historia',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Historia'),
        ),
        migrations.AlterField(
            model_name='historia',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
