# Generated by Django 3.1.1 on 2020-09-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20200904_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='video_fondo',
            field=models.CharField(default='J2qDRJdTGow', max_length=120),
        ),
    ]
