# Generated by Django 3.1.2 on 2020-10-30 21:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_equipo_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icono', models.CharField(default='icon-lightbulb', max_length=30)),
                ('nombre', models.CharField(max_length=60)),
                ('descripcion', models.TextField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(help_text='No mas de 50 Caracteres', max_length=50),
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Blogs')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='blogs/portada')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=60)),
                ('contendio', ckeditor.fields.RichTextField()),
                ('visitas', models.IntegerField(default=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.autores')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.categoria')),
            ],
        ),
    ]
