# Generated by Django 3.1.2 on 2020-12-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_auto_20201030_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosPrincipales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=60)),
                ('telefono', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=120)),
                ('facebook', models.URLField(blank=True, max_length=500, null=True)),
                ('twitter', models.URLField(blank=True, max_length=500, null=True)),
                ('linkeding', models.URLField(blank=True, max_length=500, null=True)),
                ('youtube', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': '1.1 Datos de la Aplicación',
            },
        ),
        migrations.AlterModelOptions(
            name='autores',
            options={'verbose_name_plural': '7. Autores de los Blogs'},
        ),
        migrations.AlterModelOptions(
            name='blog',
            options={'verbose_name_plural': '7.1 Entradas de Blogs'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': '6. Categoria de los Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name_plural': '4. Equipo de trabajo'},
        ),
        migrations.AlterModelOptions(
            name='historia',
            options={'verbose_name_plural': '3. Pasión e Historia'},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'verbose_name_plural': '1. Página Principal'},
        ),
        migrations.AlterModelOptions(
            name='proyectos',
            options={'verbose_name_plural': '6.1 Proyectos'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'verbose_name_plural': '5. Servicios'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name_plural': '2. Sliders'},
        ),
    ]
